[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "your_supabase_url"
  VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 